language: node_js
node_js:
 - "0.11"
 - "0.10"
after_script:
 - node_modules/.bin/istanbul cover node_modules/.bin/_mocha --report lcovonly
 - cat coverage/lcov.info | node_modules/.bin/coveralls --verbose
sudo: false
